[package]
name = "yo-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
meval = "0.2"
rand = "0.8.5"
shuffle = "0.1.7"
